### ISSUE TITLE
Entry Page Design

### ISSUE THREAD

**Issue by mattbatman** [CivicCode/uReport-client#2]
I started a quick mock of the entry page. It seems like the city has at least two card designs on their page already, one [grey](https://bloomington.in.gov/city) and one with a white background and [dark blue top border](https://bloomington.in.gov/).

Is this more or less what we had in mind? How would we handle the next step of form navigation? Would it be an intermediate page, or maybe the user is taken to a form and provided a drop-down for the sub-category?

What other information, if any, would we want on each card? We could add icons, a description of each department, the names of and links to the actual forms within each category, etc.

![grey](https://user-images.githubusercontent.com/8661427/38468444-0bd43dfe-3b14-11e8-9a70-26c05b92470a.png)
![blue-and-white](https://user-images.githubusercontent.com/8661427/38468446-0da2526a-3b14-11e8-9dd0-0102c59231b5.png)

**Comment by matt-a-t** [comment]
I like the third one with the links included in the cards, as the titles of the cards might not entirely describe everything inside (like Miscellaneous or Hazards).

Any of the designs should be very to make responsive too. We might think about having some kind of search bar at the top keep the user from having to scroll though all of the cards when they're all on top of each other.

**Comment by dpalazz** [comment]
Thanks for laying these options out! I like the third option for web (the
one with the subcategories shown). Potentially we can make it so if it's
being viewed on mobile the subcategories are not shown (and/or as Matt
said, have a search bar).
