### ISSUE TITLE
Complete Application Routing

### ISSUE THREAD

**Issue by mattbatman** [CivicCode/uReport-client#5]
Dana may have already completed this, but we need our router to switch between displaying the entry or form selection page, and the form itself. We also need to pass data from the selection page to the form (e.g. the `service_code`), and any other information necessary for the form to figure out how to populate itself.

# Essentials
- [x] Open on the entry page
- [x] Display the form component when a link to a `service_name` is clicked
- [x] Pass the `service_code` of the selected `service_name` to the form component

# Wanted
## Remembering State
- [ ] It'd be great if when a form is left early and then returned to, the form would be in the same state

**Comment by dpalazz** [comment]
Hey All - Sorry I've been MIA with my mom in town. What is priority that I
can tackle tonight?
