### ISSUE TITLE
Clean-Up for Challenge Submission

### ISSUE THREAD

**Issue by mattbatman** [CivicCode/uReport-client#7]
- [x] Publish with an open source license
- [x] Expand readme
- [x] Prepare an email for submission

**Comment by matt-a-t** [comment]
I would say let's leave the CSS/HTML markup for the site for now. We can explain somewhere (the readme?) that eventually the form itself will be inserted into the div via Javascript once it's ready to deploy.

**Comment by matt-a-t** [comment]
I just say that so they can get a clear idea of what we are thinking. Would we be interested in deploying this to Netlify or something like that to have a public url available for them to look at without having to download/run the project?

**Comment by mattbatman** [comment]
> I just say that so they can get a clear idea of what we are thinking. Would we be interested in deploying this to Netlify or something like that to have a public url available for them to look at without having to download/run the project?

On this repo, we have no server-side code, so we could also just use GitHub pages. We'd probably want to make a different branch that holds the build, if we went that route.

**Comment by mattbatman** [comment]
How do we want to handle drafting an email to submit tonight? Who wants to be responsible for hitting send?

**Comment by matt-a-t** [comment]
I can write the email after I finish the POST request tonight. Does anyone else have anything they would like to commit or am I good to send it off as soon as I am finished? I can let everyone know when I'm done if anybody wants to double check things before the final submission.

**Comment by mattbatman** [comment]
I have nothing else to commit. Personally, I'd be comfortable with you sending off a submission at your discretion.

**Comment by dpalazz** [comment]
Go for it. Let us know if you need any help with the Post.

Thanks!

**Comment by mattbatman** [comment]
@matt-a-t How are things coming?

**Comment by matt-a-t** [comment]
The post query is proving really difficult. I'm getting this error:

GraphQLError: Syntax Error: Expected Name, found :

I think I have to declare the params i'm using for the query

**Comment by mattbatman** [comment]
I've started to try to set this up, too. Are you using the [Mutation](https://www.apollographql.com/docs/react/essentials/mutations.html) component?

**Comment by matt-a-t** [comment]
I'm not right now, but I think that maybe I should be

**Comment by mattbatman** [comment]
I found these in reference to your error. I think you're on the right track: [stack](https://stackoverflow.com/questions/45404808/graphql-mutation-gives-syntax-error-expected-name) [overflow](https://stackoverflow.com/questions/45130386/graphql-syntax-error-graphql-request-515-expected-name/45131876#45131876)

**Comment by mattbatman** [comment]
Do you already have an email drafted? At this point, it may be best to call it.

**Comment by matt-a-t** [comment]
I was about to say the same thing. I'm going to keep working on it for a bit I think, I bet if I stop working without the time pressure I can figure it out.

I'll write the email now.

**Comment by mattbatman** [comment]
Thanks for all your work. I got the email. I'm going to bed. I'm sure you'll get it working 5 minutes from now.
